In [2]:
A=rand(1:4,3,3)

3×3 Matrix{Int64}:
 2  1  1
 4  1  3
 3  1  4

In [3]:
B=A
C=copy(A)
[B C]

3×6 Matrix{Int64}:
 2  1  1  2  1  1
 4  1  3  4  1  3
 3  1  4  3  1  4

In [4]:
A[1]=17
[B C]

3×6 Matrix{Int64}:
 17  1  1  2  1  1
  4  1  3  4  1  3
  3  1  4  3  1  4

In [6]:
x=ones(3)

3-element Vector{Float64}:
 1.0
 1.0
 1.0

In [7]:
a=rand(3,3)

3×3 Matrix{Float64}:
 0.556989   0.243958  0.803898
 0.180433   0.839172  0.794817
 0.0233919  0.998172  0.0395764

In [10]:
b=A*x

3-element Vector{Float64}:
 19.0
  8.0
  8.0

In [11]:
Asym=A+A'

3×3 Matrix{Int64}:
 34  5  4
  5  2  4
  4  4  8

In [12]:
Apd=A'A

3×3 Matrix{Int64}:
 314  24  41
  24   3   8
  41   8  26

In [13]:
A\b

3-element Vector{Float64}:
 1.0
 0.9999999999999992
 1.0000000000000002

In [14]:
#overdeterminded system 
Atall=A[:,1:2]
display(Atall)
Atall\b

3×2 Matrix{Int64}:
 17  1
  4  1
  3  1

2-element Vector{Float64}:
 0.8114754098360653
 5.174863387978141

In [15]:
A=rand(3,3)

3×3 Matrix{Float64}:
 0.569728   0.446424  0.990856
 0.0592037  0.390105  0.769714
 0.106725   0.361745  0.427904

In [21]:
#underdetermined system
Ashort=A[1:2,:]
display(Ashort)
Ashort\b[1:2]

2×3 Matrix{Float64}:
 0.569728   0.446424  0.990856
 0.0592037  0.390105  0.769714

3-element Vector{Float64}:
 17.867489441387505
  2.0857370124685515
  7.9620784663055675