In [1]:
my_answe=45
typeof(my_answe)

Int64

In [2]:
#Strings 

In [3]:
s1="Julia is love "


"Julia is love "

In [4]:
name="jane"
num_fingers=10
num_toes=10
println("hello my name is $name .")
println("I have $num_fingers fingers and $num_toes and total of $(num_fingers+num_toes) fingers")

hello my name is jane .
I have 10 fingers and 10 and total of 20 fingers


In [5]:
s1= " How many cats "
s2=" how many cats are too many cats "
string(s1, 10 ,s2)

" How many cats 10 how many cats are too many cats "

In [6]:
s1*s2 

" How many cats  how many cats are too many cats "

In [7]:
"$s1$s2"

" How many cats  how many cats are too many cats "

In [8]:
#datstructures 
#1. Ditionaries 
#2. Tuples 
#3 . Arrays

In [9]:
myphonebook=Dict("Jenny"=> "8810624934","ghostbusters"=>"9616940085")

Dict{String, String} with 2 entries:
  "Jenny"        => "8810624934"
  "ghostbusters" => "9616940085"

In [10]:
myphonebook["Kramer"]="555009"

"555009"

In [11]:
myphonebook 

Dict{String, String} with 3 entries:
  "Jenny"        => "8810624934"
  "Kramer"       => "555009"
  "ghostbusters" => "9616940085"

In [12]:
myphonebook["Kramer"]

"555009"

In [13]:
pop!(myphonebook,"Kramer")

"555009"

In [14]:
myphonebook 


Dict{String, String} with 2 entries:
  "Jenny"        => "8810624934"
  "ghostbusters" => "9616940085"

In [15]:
#Tuples 

In [16]:
myfavproglang=("c++","python","Julia")

("c++", "python", "Julia")

In [17]:
myfavproglang[1]

"c++"

In [18]:
#julia is one indexed not zero indexed 

In [19]:
 #Arrays 

In [20]:
myfavsub=["COA","OPs","ML"]

3-element Vector{String}:
 "COA"
 "OPs"
 "ML"

In [21]:
myfavsub[1]

"COA"

In [22]:
array=["njixne3",1,2,3,4,5]

6-element Vector{Any}:
  "njixne3"
 1
 2
 3
 4
 5

In [23]:
array[1]=3

3

In [24]:
array

6-element Vector{Any}:
 3
 1
 2
 3
 4
 5

In [25]:
push!(array,34)

7-element Vector{Any}:
  3
  1
  2
  3
  4
  5
 34

In [26]:
array

7-element Vector{Any}:
  3
  1
  2
  3
  4
  5
 34

In [27]:
pop!(array)

34

In [28]:
array

6-element Vector{Any}:
 3
 1
 2
 3
 4
 5

In [29]:
numbers=[[1,2,3],[4,5],[2,3,4,5,6]]

3-element Vector{Vector{Int64}}:
 [1, 2, 3]
 [4, 5]
 [2, 3, 4, 5, 6]

In [30]:
rand(4,3)

4×3 Matrix{Float64}:
 0.912189  0.648272  0.100523
 0.461399  0.92889   0.109849
 0.116487  0.570886  0.977186
 0.372848  0.320913  0.72461

In [31]:
rand(4,3,2)

4×3×2 Array{Float64, 3}:
[:, :, 1] =
 0.28021    0.193322  0.835172
 0.532776   0.194533  0.891155
 0.0535921  0.433156  0.781056
 0.681008   0.795036  0.976954

[:, :, 2] =
 0.898942  0.52073    0.766633
 0.603456  0.958805   0.713108
 0.477448  0.0501816  0.265514
 0.972999  0.688322   0.670255

In [32]:
#loops 

In [33]:
#while 
myfreinds=["Ted","BONNY","Kanishk"]
i=1
while i<=length(myfreinds)
    friend=myfreinds[i]
    println("hi $friend ,it's great to meet you")
    i+=1
end

hi Ted ,it's great to meet you
hi BONNY ,it's great to meet you
hi Kanishk ,it's great to meet you


In [34]:
#for 
for friends in myfreinds
    println("hello $friends")
end

hello Ted
hello BONNY
hello Kanishk


In [35]:
m,n=5,5
A=zeros(m,n)
A

5×5 Matrix{Float64}:
 0.0  0.0  0.0  0.0  0.0
 0.0  0.0  0.0  0.0  0.0
 0.0  0.0  0.0  0.0  0.0
 0.0  0.0  0.0  0.0  0.0
 0.0  0.0  0.0  0.0  0.0

In [36]:
for i in 1:m
    for j in 1:n
        A[i,j]=i+j
    end
end
A

5×5 Matrix{Float64}:
 2.0  3.0  4.0  5.0   6.0
 3.0  4.0  5.0  6.0   7.0
 4.0  5.0  6.0  7.0   8.0
 5.0  6.0  7.0  8.0   9.0
 6.0  7.0  8.0  9.0  10.0

In [37]:
B=zeros(m,n)
B

5×5 Matrix{Float64}:
 0.0  0.0  0.0  0.0  0.0
 0.0  0.0  0.0  0.0  0.0
 0.0  0.0  0.0  0.0  0.0
 0.0  0.0  0.0  0.0  0.0
 0.0  0.0  0.0  0.0  0.0

In [38]:
for i in 1:m , j in 1:n
        B[i,j]=i+j
end
B

5×5 Matrix{Float64}:
 2.0  3.0  4.0  5.0   6.0
 3.0  4.0  5.0  6.0   7.0
 4.0  5.0  6.0  7.0   8.0
 5.0  6.0  7.0  8.0   9.0
 6.0  7.0  8.0  9.0  10.0

In [39]:
#now more julian way of doing things 

In [40]:
#array comprehension 
C=[i+j for i in 1:m,j in 1:n]

5×5 Matrix{Int64}:
 2  3  4  5   6
 3  4  5  6   7
 4  5  6  7   8
 5  6  7  8   9
 6  7  8  9  10

In [41]:
for n in 1:10
    A=[i+j for i in 1:n, j in 1:n]
    display(A)
end

1×1 Matrix{Int64}:
 2

2×2 Matrix{Int64}:
 2  3
 3  4

3×3 Matrix{Int64}:
 2  3  4
 3  4  5
 4  5  6

4×4 Matrix{Int64}:
 2  3  4  5
 3  4  5  6
 4  5  6  7
 5  6  7  8

5×5 Matrix{Int64}:
 2  3  4  5   6
 3  4  5  6   7
 4  5  6  7   8
 5  6  7  8   9
 6  7  8  9  10

6×6 Matrix{Int64}:
 2  3  4   5   6   7
 3  4  5   6   7   8
 4  5  6   7   8   9
 5  6  7   8   9  10
 6  7  8   9  10  11
 7  8  9  10  11  12

7×7 Matrix{Int64}:
 2  3   4   5   6   7   8
 3  4   5   6   7   8   9
 4  5   6   7   8   9  10
 5  6   7   8   9  10  11
 6  7   8   9  10  11  12
 7  8   9  10  11  12  13
 8  9  10  11  12  13  14

8×8 Matrix{Int64}:
 2   3   4   5   6   7   8   9
 3   4   5   6   7   8   9  10
 4   5   6   7   8   9  10  11
 5   6   7   8   9  10  11  12
 6   7   8   9  10  11  12  13
 7   8   9  10  11  12  13  14
 8   9  10  11  12  13  14  15
 9  10  11  12  13  14  15  16

9×9 Matrix{Int64}:
  2   3   4   5   6   7   8   9  10
  3   4   5   6   7   8   9  10  11
  4   5   6   7   8   9  10  11  12
  5   6   7   8   9  10  11  12  13
  6   7   8   9  10  11  12  13  14
  7   8   9  10  11  12  13  14  15
  8   9  10  11  12  13  14  15  16
  9  10  11  12  13  14  15  16  17
 10  11  12  13  14  15  16  17  18

10×10 Matrix{Int64}:
  2   3   4   5   6   7   8   9  10  11
  3   4   5   6   7   8   9  10  11  12
  4   5   6   7   8   9  10  11  12  13
  5   6   7   8   9  10  11  12  13  14
  6   7   8   9  10  11  12  13  14  15
  7   8   9  10  11  12  13  14  15  16
  8   9  10  11  12  13  14  15  16  17
  9  10  11  12  13  14  15  16  17  18
 10  11  12  13  14  15  16  17  18  19
 11  12  13  14  15  16  17  18  19  20

In [42]:
x=9
y=10
if x > y
    println(x)
else 
    println(y)
end

10


In [43]:
#functions 
function sayhi(name)
    println("Hello $name")
end

sayhi (generic function with 1 method)

In [44]:
sayhi("suyash")

Hello suyash


In [45]:
#anonymus function 

In [46]:
sayhi2=name->println("hehllo $name")
square=x->x^2

#7 (generic function with 1 method)

In [47]:
sayhi2("suyash")


hehllo suyash


In [48]:
square(2)

4

In [49]:
#duck typing in julia 

In [50]:
#if it quacks like a duck , it's a duck."
v=rand(3,3)

3×3 Matrix{Float64}:
 0.245613  0.143544  0.710781
 0.611254  0.469895  0.0206121
 0.684097  0.524198  0.948812

In [51]:
square(v)

3×3 Matrix{Float64}:
 0.634311  0.475298  0.851934
 0.451457  0.319348  0.46371
 1.13752   0.841882  1.39729

In [52]:
#this works because square of a matrix is well defined 
v2=rand(3)

3-element Vector{Float64}:
 0.6260316679014707
 0.007710480415127452
 0.4662988082781867

In [53]:
square(v2)

LoadError: MethodError: no method matching ^(::Vector{Float64}, ::Int64)
Closest candidates are:
  ^(::Union{AbstractChar, AbstractString}, ::Integer) at /Applications/Julia-1.7.app/Contents/Resources/julia/share/julia/base/strings/basic.jl:721
  ^(::LinearAlgebra.UniformScaling, ::Number) at /Applications/Julia-1.7.app/Contents/Resources/julia/share/julia/stdlib/v1.7/LinearAlgebra/src/uniformscaling.jl:318
  ^(::Rational, ::Integer) at /Applications/Julia-1.7.app/Contents/Resources/julia/share/julia/base/rational.jl:475
  ...

In [54]:
#this happened because square on 1 d array in not defined

In [55]:
#mutating vs non- mutating function

In [56]:
v=[4,3,5]
# sort() will give the output but will not alter the element of that array but sort!() will alter the element 
sort(v)


3-element Vector{Int64}:
 3
 4
 5

In [57]:
v

3-element Vector{Int64}:
 4
 3
 5

In [58]:
sort!(v)

3-element Vector{Int64}:
 3
 4
 5

In [59]:
v

3-element Vector{Int64}:
 3
 4
 5

In [60]:
#broadcasting f.()
A=rand(3,3)

3×3 Matrix{Float64}:
 0.260583  0.153432  0.111916
 0.29766   0.937099  0.776231
 0.139473  0.862067  0.70579

In [61]:
square(A)

3×3 Matrix{Float64}:
 0.129183  0.280241  0.227251
 0.464765  1.59299   1.30857
 0.391386  1.43768   1.18291

In [62]:
C=[1,2,3]
square.(C)

3-element Vector{Int64}:
 1
 4
 9

In [63]:
square.(A)

3×3 Matrix{Float64}:
 0.0679035  0.0235413  0.0125251
 0.0886017  0.878154   0.602535
 0.0194526  0.743159   0.49814